### ISSUE TITLE
[bug] numbered nested toc not correctly formatted

### ISSUE THREAD

**Issue by AskMeAgain** [BlueBoxWare/TocMe#3]
Hi,

when using your plugin to generate a numbered nested toc, then the indentation of the sublist is not correct (for github for example). I used the GitHub variant, but any other variant also doesnt change here anything:

This is the generated markdown:

```
4. [Module Structure ](#module-structure-)
5. [Architecture ](#architecture-)
  1. [Meshinery Processors ](#meshinery-processors-)
  2. [MeshineryTasks ](#meshinerytasks-)
```

the readme in github:

![Unbenannt](https://user-images.githubusercontent.com/20632124/146677327-60bbd622-8639-4954-af9f-56ae3cc1cd1a.PNG)

Note: if you disable the numbers, then the indentation is correct

**Comment by BlueBoxWare** [comment]
Should be fixed now. Turns out nested lists in numbered lists need 3 spaces as indentation instead of 2. Thanks for the report!
