### ISSUE TITLE
[feature-request] include md files in same folder for toc

### ISSUE THREAD

**Issue by AskMeAgain** [BlueBoxWare/TocMe#4]
Hi,

i have differemt md files sitting in the same folder and i would like to include a toc to these files.

Is something like that possible? 

Thanks

**Comment by BlueBoxWare** [comment]
This should work, if I understand you correctly:

```groovy
tocme {

    fileTree("some folder").include("*.md").visit { file ->
        doc(file.file)
    }

}
```

Or do you mean to create a TOC with links to the other files in the directory?

**Comment by AskMeAgain** [comment]
I have 3 Files in my folder:

* a.md
* b.md
* c.md

I would like to include

* a toc in a.md which redirects to b.md and c.md
* another toc in b.md which redirects to a.md and c.md etc

But after thinking a bit more, maybe such a feature is not really needed and if you have that much md's sitting around you should use the github wiki anyway :)

**Comment by BlueBoxWare** [comment]
Aha, I see. Although that would be useful, I rather not add such functionality because it would complicate things quite a bit.
