### ISSUE TITLE
All tocme tasks are skipped with reason NO-SOURCE with Gradle 8

### ISSUE THREAD

**Issue by dannyvalentesonos** [BlueBoxWare/TocMe#5]
## Summary

When running any tocme task, using Gradle 8, the task is skipped, with the following information:

```
> Task :insertTocs NO-SOURCE
Skipping task ':insertTocs' as it has no source files and no previous output files.
```

Going back to Gradle 7.6 resolves the problem.

**Comment by dannyvalentesonos** [comment]
I've tracked it down to
```
@InputFiles
  @SkipWhenEmpty
  @Optional
  fun getInputFiles() = if (getOutputFiles().isNotEmpty()) listOf(File("__DummyF1l3__")) else null
```
Gradle 8 must not like when a file that doesn't exist is used as InputFiles.

**Comment by dannyvalentesonos** [comment]
If I actually create a file called `__DummyF1l3__` in my project directory, then the tocme tasks run properly.

**Comment by BlueBoxWare** [comment]
Thanks for the report and looking into this! That function was indeed the problem. It should be fixed now.

**Comment by dannyvalentesonos** [comment]
Thanks for the quick fix!! I can confirm it works perfectly now.
